 version: '2'
 services:

  web:
     build:
          context: ./
     command: sh docker-command.sh
     volumes:
       - .:/code
     ports:
       - 8000:8000
     depends_on:
       - db


  db:
     image: postgres
     environment:
       POSTGRES_USER: docker
       POSTGRES_PASSWORD: docker
     ports:
       - 5432:5432
     expose:
       - 5432

